### ISSUE TITLE
这是个很大的漏洞啊

### ISSUE THREAD

**Issue by masteryub** [Leslin/thinkphp5-restfulapi#15]
![1555144964(1)](https://user-images.githubusercontent.com/26316199/56077143-38140c80-5e0b-11e9-842e-141c62291ed7.jpg)

**Comment by Leslin** [comment]
老哥，这个是给的开发提示，提示正确的签名是怎样的。

**Comment by masteryub** [comment]
哦哦这要是谁不改那认证就失效了

**Comment by Leslin** [comment]
是的，只是方便开发者调试，判断签名是不是一致
