### ISSUE TITLE
刷新token啥时候用

### ISSUE THREAD

**Issue by Ynwasususama** [Leslin/thinkphp5-restfulapi#17]
客户端对请求是不是还要做什么判断啊 如果返回的是过期还要去刷新吗 那客户端每次ajax请求都要重复写一段去判断是否过期刷新的代码吗

**Comment by Leslin** [comment]
生成了token，会把token过期时间一起返回给客户端，客户端缓存起来，在每次请求的时候判断下过期时间是否已经过期了，如果过期了，那就用原来的token调用刷新token的接口，生成一个新token，就不需要重新算签名去获取token。

**Comment by lovehamburger** [comment]
刷新令牌和  重新调用token 处理代码简洁些外有什么区别吗？  不断的获取token  不就是在刷新了吗？  我现在有个疑问是重复获取token的时候怎么让之前生成的，没有过期的token 失效呢？  只能等2个小时吗？  或者写个中控服务 判断是否重复获取？

**Comment by Leslin** [comment]
> 刷新令牌和 重新调用token 处理代码简洁些外有什么区别吗？ 不断的获取token 不就是在刷新了吗？ 我现在有个疑问是重复获取token的时候怎么让之前生成的，没有过期的token 失效呢？ 只能等2个小时吗？ 或者写个中控服务 判断是否重复获取？

不断的获取token不是刷新，是生成很多token，在有效期内都是有效的，一般业务上不推荐这样，刷新token是使用老的token唤起新的token，老的会立即失效，如果重新生成token，让之前的token失效，需要在生成token的时候带上老的token，或者cache用户token的前缀使用户唯一标记进行缓存，生成时候就覆盖掉老的，
