### ISSUE TITLE
重复获取token  怎么删除之前的旧token

### ISSUE THREAD

**Issue by lovehamburger** [Leslin/thinkphp5-restfulapi#24]
刷新令牌和 重新调用token 处理代码简洁些外有什么区别吗？ 不断的获取token 不就是在刷新了吗？ 我现在有个疑问是重复获取token的时候怎么让之前生成的，没有过期的,  token 失效呢？ 只能等2个小时吗？ 或者写个中控服务 判断是否重复获取token？

**Comment by Leslin** [comment]
在另外个lssuses中回复了，需要保持唯一，可以使用用户名进行缓存key，cache($account,$token),每次生成会覆盖老的token

**Comment by lovehamburger** [comment]
是，这也是个方法，但是按这个 刷新令牌 和 重新调用token的接口 就有点雷同了，也可以完全不用刷新token这个接口对吧

**Comment by GitDuXiangJie** [comment]
为什么你来沟通 邮件会发到我这里啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Leslin/thinkphp5-restfulapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 上午10:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Leslin/thinkphp5-restfulapi] 重复获取token  怎么删除之前的旧token (Issue #24)





 
是，这也是个方法，但是按这个 刷新令牌 和 重新调用token的接口 就有点雷同了，也可以完全不用刷新token这个接口对吧

**Comment by Leslin** [comment]
> 是，这也是个方法，但是按这个 刷新令牌 和 重新调用token的接口 就有点雷同了，也可以完全不用刷新token这个接口对吧

有很多场景的，比方用户第一次登陆的时候会输入手机号、密码各种加密后登录生成token，token有效期7200s，当7000秒的时候，需要重新换取token，这个时候要是调用token生成，需要手机号、密码、加密等又走一遍，有些密码等数据是不存客户端的，这个时候就可以用旧token直接生成新token了，这个就是刷新令牌的作用

**Comment by lovehamburger** [comment]
好的，谢谢了呢

**Comment by GitDuXiangJie** [comment]
人麻了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Leslin/thinkphp5-restfulapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Leslin/thinkphp5-restfulapi] 重复获取token  怎么删除之前的旧token (Issue #24)





 
Closed #24.

**Comment by lovehamburger** [comment]
这么神奇
